collections:
 pages:
         output: true
         url: pages
 transcripts:
         output: true
         url: transcripts
         sort_by: capitulo


defaults:
  - scope:
      path: "_pages"
    values:
          layout: comicpage
          imagen: ksbdcoverchapter1.webp
          alt: MATA SEIS BILLONES DE DEMONIOS
          capitulo: 99
          pagina: 99
          libro: 99
          creditos: Duende Inexistente
          oglink: 
repository: DuendeInexistente/m6bd